name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the sections below.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Clear and concise description of the bug.
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Minimal steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should have happened instead?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened? Include screenshots if applicable.
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Where does the bug occur?
      multiple: true
      options:
        - Desktop GitHub
        - Mobile GitHub
        - Local build
        - GitHub Actions CI
    validations:
      required: true

  - type: textarea
    id: root-cause
    attributes:
      label: Root Cause Analysis
      description: If you've investigated, describe the root cause.

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: If you have a fix in mind, describe the approach.
