name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea below.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Clear and concise description of the feature.
      placeholder: What do you want to add or change?
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this feature needed? What problem does it solve?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
      description: How should this be implemented? Include technical details if relevant.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative approaches you've considered.

  - type: dropdown
    id: scope
    attributes:
      label: Scope
      description: What area does this affect?
      multiple: true
      options:
        - SVG rendering
        - Animation
        - GitHub API / Data
        - CI/CD
        - Configuration
        - Documentation
    validations:
      required: true
